import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import MainHeader from '@/components/common/MainHeader';
import MainFooter from '@/components/common/MainFooter';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'ALPHASOFTX LIMITED',
	description: 'Generated by ALPHASOFTX LIMITED',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<MainHeader />
				{children}
				<MainFooter />
			</body>
		</html>
	);
}
